### ISSUE TITLE
Release 1.1.0 on Pypi

### ISSUE THREAD

**Issue by mikaelengstrom** [raiderrobert/django-multiurl#17]
It would be great if you could release the Django 1.9 compatible version on pypi.

Thanks.

**Comment by raiderrobert** [comment]
@mikaelengstrom will try to get to this over the holiday.Had a pretty busy past few weeks IRL.

**Comment by mikaelengstrom** [comment]
@raiderrobert, any update on this?  I am going to release a project based on this lib and it would be great to pinpoint it to a release instead of the master-branch. 

Let me know if I can do anything to help you out.

**Comment by raiderrobert** [comment]
@mikaelengstrom, sorry for the delay. I've released it just now, and I've tested that it's up on pypi.

Hope I haven't caused any delays on your part.
