### ISSUE TITLE
Add-in support for Django 2.0

### ISSUE THREAD

**Issue by raiderrobert** [raiderrobert/django-multiurl#26]
Django 2.0 drops with big changes to how urls work, but also Python 2 deprecation. Need to handle the Python 2 deprecation more gracefully.

**Comment by seospace** [comment]
Hello! Any news on this?

**Comment by raiderrobert** [comment]
@seospace, 👍 just haven't got to it yet! Willing to take a PR with passing tests!

**Comment by seospace** [comment]
@raiderrobert I am at the beginning of my path to master Django, still reading the documentation, it's my 3rd day :)

But i was about to study your code, maybe... who knows 💃

**Comment by raiderrobert** [comment]
@seospace welcome to the Django community!

**Comment by mikaelengstrom** [comment]
@raiderrobert Would you be fine with bumping the major version and maintain the python2/django1 in a separate branch?

Played around with the code and it got kind of hacky to support both.

**Comment by raiderrobert** [comment]
@mikaelengstrom oh yes, that would be fine. That's why I started a 2.x and 1.x branch about 9 months back. So they can evolve separately.

**Comment by mikaelengstrom** [comment]
@raiderrobert Oh, I thought those were stale branches :)

I did a quick patch for DJ2 that work with V1 and V2 since i needed it right away. You might want to consider merging it: https://github.com/raiderrobert/django-multiurl/pull/28

**Comment by raiderrobert** [comment]
@mikaelengstrom thanks a bunch!
