### ISSUE TITLE
`multiurl()` can break decorator/middleware behaviour on wrapped views.

### ISSUE THREAD

**Issue by mrmachine** [raiderrobert/django-multiurl#7]
I have some views wrapped by `multiurl()`. One has a form upload and I want to modify the upload handlers list on the fly as per the Django docs.

I decorate my view with @csrf_exempt and have it wrap a private view function which is decorated with @csrf_protect.

But `CsrfViewMiddleware` sees `multiview` as the view function, and `multiview` does not have a `csrf_exempt` attribute.

I'm not sure what would be the correct approach here. Add a kwarg to `multiurl()` for a decorator (or multiple decorators) and apply them to the `multiview()` function that gets created?

But even then, those decorators may not applicable to all the wrapped views.

There might be other similar compatibility issues with middleware that make use of decorators to alter behaviour for specific view functions.

**Comment by raiderrobert** [comment]
Doing some clean up, because this is so old, and I frankly don't know if it's a problem any more. 

Feel free to comment someone if you're into this issue.
